version: '3.1'

services:

  rabbitmq:
    image: quay.io/ukhomeofficedigital/rabbitmq:v3.6.6
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - hocs-network
    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  reporting:
    build:
      context: .
    environment:
      spring.profiles.active: postgres
      db.host: postgres
      db.username: root
      db.password: dev
    depends_on:
      - postgres
      - rabbitmq
    ports:
      - 8082:8080
    networks:
      - hocs-network

networks:
  hocs-network: