version: '3.1'

services:

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hocs-network

  postgres:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - hocs-network
    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: dev
    tmpfs:
      - /var/lib/postgresql

  reporting:
    build:
      context: .
    environment:
      spring.profiles.active: postgres
      db.host: postgres
      db.username: root
      db.password: dev
      env.rabbit.mq.host: rabbitmq
    depends_on:
      - postgres
    ports:
      - 8082:8080
    networks:
      - hocs-network

networks:
  hocs-network: