version: '3.1'

services:

  postgres:
    image: postgres
    ports:
      - 5432:5432
    networks:
      - hocs-network
    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: dev
    volumes:
      - dbdata:/var/lib/postgresql

  reporting:
    build:
      context: .
    environment:
      spring.profiles.active: postgres
      db.host: postgres
      db.user: root
      db.pass: dev
    depends_on:
      - postgres
    ports:
      - 8082:8080
    networks:
      - hocs-network
    command: /app/scripts/run.sh
    volumes:
      - ../hocs-data/data/:/app/data/
networks:
  hocs-network:

volumes:
  dbdata: {}