version: '3.1'

services:

  database:
    image: postgres

    ports:
      - 5432:5432

    networks:
      - reporting-network

    environment:
     POSTGRES_USER: root
     POSTGRES_PASSWORD: dev

    volumes:
      - dbdata:/var/lib/postgresql

  reporting:
    build:
      context: .

    environment:
      spring.profiles.active: postgres
      server.port: 8080
      reporting.db.hostname: database
      reporting.db.username: root
      reporting.db.password: dev
      reporting.db.name: postgres
      reporting.db.port: 5432
      reporting.schema.name: public
      hostname: reporting:8080

    depends_on:
      - database

    ports:
      - 9001:8080

    networks:
      - reporting-network

    command: /app/scripts/run.sh

    volumes:
      - ../hocs-data/data/:/app/data/

networks:
  reporting-network:

volumes:
  dbdata: {}